// Code generated by hertz generator.

package oyasumi

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/soladxy/oyasumi/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.LogMw}
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checksslMw() []app.HandlerFunc {
	// your code...
	return nil
}
