// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWebsite = "website"

// Website mapped from table <website>
type Website struct {
	WebsiteID string         `gorm:"column:website_id;primaryKey" json:"website_id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Domain    string         `gorm:"column:domain" json:"domain"`
	ShareID   string         `gorm:"column:share_id" json:"share_id"`
	ResetAt   time.Time      `gorm:"column:reset_at" json:"reset_at"`
	UserID    string         `gorm:"column:user_id" json:"user_id"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy string         `gorm:"column:created_by" json:"created_by"`
	TeamID    string         `gorm:"column:team_id" json:"team_id"`
}

// TableName Website's table name
func (*Website) TableName() string {
	return TableNameWebsite
}
