// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/soladxy/oyasumi/biz/service/website"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/soladxy/oyasumi/biz/consts"
	"github.com/soladxy/oyasumi/biz/container"
	oyasumi "github.com/soladxy/oyasumi/biz/model/oyasumi"
	"github.com/soladxy/oyasumi/biz/util"
)

// HelloMethod .
// @router /api/hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext, container *container.Container) {
	var err error
	var req oyasumi.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		util.SendErrResponse(c, consts.ParamErr)
		return
	}

	websiteService := website.NewWebsiteService(container)

	info, err := websiteService.GetLatestWebsiteInfo(ctx)
	if err != nil {
		hlog.CtxErrorf(ctx, "[HelloMethod] GetLatestWebsiteInfo Err: %v", err)
		util.SendErrResponse(c, consts.DownstreamErr)
		return
	}

	resp := new(oyasumi.HelloResp)
	resp.Data = &oyasumi.HelloData{
		Now:        time.Now().Format(time.DateTime),
		DbTestData: info,
	}

	util.SendSuccessResponse(c, resp)
}
