// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/soladxy/oyasumi/biz/config"
	"github.com/soladxy/oyasumi/biz/dal/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitService(path string) (*Container, error) {
	configConfig, err := config.NewServiceConfig(path)
	if err != nil {
		return nil, err
	}
	iMySQL, err := mysql.NewMySQL(configConfig)
	if err != nil {
		return nil, err
	}
	container := &Container{
		MySQL: iMySQL,
	}
	return container, nil
}

func InitGormGen(path string) (*gorm.DB, error) {
	configConfig, err := config.NewServiceConfig(path)
	if err != nil {
		return nil, err
	}
	db, err := mysql.NewGenDBClient(configConfig)
	if err != nil {
		return nil, err
	}
	return db, nil
}

// wire.go:

type Container struct {
	MySQL mysql.IMySQL
}
