// Code generated by hertz generator.

package oyasumi

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	oyasumi "github.com/soladxy/oyasumi/biz/model/oyasumi"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req oyasumi.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(oyasumi.HelloResp)

	c.JSON(consts.StatusOK, resp)
}
